# ~/.config/starship.toml

[git_state]
disabled = true

[git_status]
disabled = true

[character]
success_symbol = "[λ](bold green)"
error_symbol   = "[λ](bold red)"

[custom]

[custom.tab]
description = "The current tab in the tab terminal multiplexer"
command = "tab --starship"
when = "tab --starship"
shell = ["sh"]
format = "[$output]($style) "
style = "bold blue"
