# ~/.config/starship.toml

continuation_prompt = "[▶   ](bright-black)"

right_format = "$all"
format       = "$character"
# right_format = """$git_branch$git_status$cmd_duration$directory"""
# format       = "$all"
add_newline  = false

scan_timeout = 10

[character]
success_symbol = " [](bold green)"
error_symbol   = " [](bold red)"
vicmd_symbol   = "[  ](bold yellow)"

[hostname]
ssh_only = true
format = "[$hostname](bold blue) "
disabled = false

[directory]
style = "white"

[sudo]
style = "bold red"
# symbol = "#"
format = "[$symbol]($style)"
disabled = false

[custom.tab]
description = "The current tab in the tab terminal multiplexer"
command = "tab --starship"
when = "tab --starship"
shell = ["sh"]
format = "[$output]($style) "
style = "bold blue"

[git_branch]
format = "[$symbol$branch ]($style)"
style = "bright-white"
symbol = "🌱 "

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
disabled = true

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

